backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages-slo"
    label: "Pages SLO"
    files:
      - file: "src/pages/slo/index.md"
        label: "Prva stran"
        name: "prva-stran"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/oddaja-dela-za-zaposlene/index.md"
        label: "Oddaja dela za zaposlene"
        name: "oddaja-dela-za-zaposlene"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/oddaja-dela/index.md"
        label: "Oddaja dela"
        name: "oddaja-dela"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/uvodnik/index.md"
        label: "Uvodnik"
        name: "uvodnik"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/pqdt/index.md"
        label: "Pqdt"
        name: "pqdt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/pogoji-uporabe/index.md"
        label: "Pogoji uporabe"
        name: "pogoji-uporabe"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/api/index.md"
        label: "API"
        name: "api"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/slo/knjiznice-um/index.md"
        label: "Knjiznice UM"
        name: "knjiznice-um"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages-eng"
    label: "Pages ENG"
    files:
      - file: "src/pages/eng/index.md"
        label: "Prva stran"
        name: "prva-stran"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/document-upload-for-employees/index.md"
        label: "Document Upload For Employees"
        name: "document-upload-for-employees"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/upload-document/index.md"
        label: "Upload document"
        name: "upload-document"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/introduction/index.md"
        label: "Introduction"
        name: "introduction"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/pqdt/index.md"
        label: "Pqdt"
        name: "pqdt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/policies/index.md"
        label: "Policies"
        name: "policies"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/eng/um-libraries/index.md"
        label: "UM libraries"
        name: "um-libraries"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "content-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Header", name: "header", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
